layout_spectrum: 0.6755528
typography_spectrum: 0.6542982
color:
  saturation: 0.4103218
  lightness: 0.3747062
  brandStrength: 0.889528
  rhythmicContrast: 0.4970354
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Jenny-Lynn Sheldon
